name: Update Files JSON

# Bisa jalan otomatis saat push ke main
# Bisa juga dijalankan manual via "Run workflow"
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # penting biar bisa push balik

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Jalankan script generate_files.py
      - name: Jalankan generate_files.py
        run: python generate_files.py

      # 4️⃣ Commit & Push files.json jika ada perubahan
      - name: Commit & Push files.json
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Konfigurasi user git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Tambahkan files.json
          git add files.json

          # Cek perubahan
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan untuk di-commit."
            exit 0
          fi

          # Commit perubahan
          git commit -m "Auto-update files.json"

          # Push pake PAT
          git push https://x-access-token:${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \
          echo "⚠️ Push gagal, workflow tetap selesai."