name: Update Files JSON

on:
  push:
    branches: [ main ]
    paths:
      - "files/**"     # hanya jalan kalau ada file di folder files yang berubah
  workflow_dispatch:    # bisa dijalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate files.json
        run: python generate_files.py

      - name: Commit & push files.json jika berubah
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files.json
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan untuk di-commit."
            exit 0
          fi
          git commit -m "⚡ Auto-update files.json ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \
          echo "⚠️ Push gagal, workflow tetap selesai."
