name: Update Files JSON

on:
  push:
    paths:
      - "files/**"   # kalau ada file di dalam folder files berubah

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Jalankan generate_files.py
        run: python generate_files.py

      - name: Commit dan Push perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add files.json
          git commit -m "Auto-update files.json"
          git push
