name: Update Files JSON

on:
  push:
    branches: [ main ]
    paths:
      - "files/**"      # hanya jalan kalau ada perubahan di folder files
  workflow_dispatch:    # bisa dijalankan manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Run Python to update JSON
        run: python generate_files.py   # <-- ini bikin file JSON terbaru

      - name: Commit & push JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files.json
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan untuk di-commit."
            exit 0
          fi
          git commit -m "⚡ Auto-update files.json ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \
          echo "⚠️ Push gagal, workflow tetap selesai."
