name: Update Files JSON

on:
  push:
    branches: [ main ]
    paths:
      - "files/**"      # workflow ini hanya jalan kalau ada perubahan di folder files
  workflow_dispatch:    # bisa dijalankan manual juga lewat GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest  # pake runner Ubuntu terbaru

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # <-- checkout repo supaya bisa baca & ubah files.json

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        # <-- install Python versi 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"
        # <-- install library Python kalau ada, kalau ga ada tetep lanjut

      - name: Run Python to update JSON
        run: python generate_files.py
        # <-- jalanin script Python untuk bikin/update files.json

      # ================= DEBUG STEPS =================
      - name: List folder contents for debug
        run: |
          echo "=== Folder debug ==="
          for folder in files/aplikasi files/configs files/scripts files/video files/arsip; do
            echo "Folder: $folder"
            if [ -d "$folder" ]; then
              ls -l "$folder"
            else
              echo "Folder tidak ada"
            fi
            echo "-------------------"
          done
        # <-- step ini ngecek folder-folder ada isinya atau tidak di runner
        #     berguna buat debugging kalau generate_files.py gagal bikin file

      - name: Show generated files.json
        run: cat files.json
        # <-- nge-print isi files.json di log supaya bisa dicek hasil generate Python
      # =================================================

      - name: Commit & push JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files.json
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan untuk di-commit."
            exit 0
          fi
          git commit -m "⚡ Auto-update files.json ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \
          echo "⚠️ Push gagal, workflow tetap selesai."
        # <-- step ini commit & push files.json ke main
        #     catatan penting:
        #     1. GITHUB_TOKEN default punya akses write ke repo private/public
        #     2. Push bisa gagal kalau repo protected branch atau PAT/permission kurang
        #     3. `|| echo ...` supaya workflow tetep selesai walau push gagal
