name: Update

on:
push:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest

steps:  
  - name: Checkout repo  
    uses: actions/checkout@v3  
    with:  
      fetch-depth: 0   # penting biar bisa push balik  

  - name: Setup Python  
    uses: actions/setup-python@v4  
    with:  
      python-version: '3.x'  

  - name: Jalankan generate_files.py  
    run: python generate_files.py  

  - name: Commit & push files.json jika berubah  
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      GITHUB_REPOSITORY: ${{ github.repository }}  
    run: |  
      git config user.name "github-actions[bot]"  
      git config user.email "github-actions[bot]@users.noreply.github.com"  
      git add files.json  
      if git diff --cached --quiet; then  
        echo "✅ Tidak ada perubahan untuk di-commit."  
        exit 0  
      fi  
      git commit -m "Auto-update files.json"  
      git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \  
      echo "⚠️ Push gagal, workflow tetap selesai."